name: test

on:
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Install external library
      #   run: sudo apt-get update && sudo apt-get install -y ghostscript poppler-utils
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn playwright-core install chromium
      - run: yarn build
      - run: yarn test
  build-and-push-image:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3
      - name: Output current package version
        id: package
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Output current Playwright version
        id: playwright
        run: |
          yarn install --frozen-lockfile
          VERSION=$(node -e 'console.log(require("playwright-core/package.json").version)')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            VS_CLI_VERSION=${{ steps.package.outputs.version }}
            PLAYWRIGHT_VERSION=${{ steps.playwright.outputs.version }}
          tags: localhost:5000/vivliostyle/cli:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/vivliostyle/cli:latest
